(() => {
  const KEY="cham-blog-v1", ADMIN_KEY="cham-admin-v1";
  const images={planning:"https://images.unsplash.com/photo-1455390582262-044c1008a2b9?auto=format&fit=crop&w=900&q=80",memory:"https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=80",ai:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",group:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=80",time:"https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=900&q=80",web:"https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80",aiCareer:"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80",cv:"https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80"};
  const initial=[
    {id:"plan",title:"Lập kế hoạch học tập mà không tự làm khó mình",category:"Học tập",date:"2026-09-24",author:"An Nguyễn",minutes:6,image:images.planning,excerpt:"Một kế hoạch tốt không cần kín lịch. Nó cần đủ rõ để bạn biết bước tiếp theo là gì.",content:"<p>Đầu kỳ, mình thường hào hứng tải về đủ loại ứng dụng quản lý rồi lên một chiếc lịch kín mít. Đến tuần thứ hai thì kế hoạch bắt đầu trượt, và mình nghĩ chắc bản thân thiếu kỷ luật. Sau này mình nhận ra kế hoạch ấy đơn giản là không dành chỗ cho một cuộc sống thật.</p><h3>Bắt đầu bằng việc nhìn toàn cảnh</h3><p>Ghi lại ngày thi, hạn nộp bài và những buổi cố định trong tuần. Sau đó mới chia bài lớn thành những việc nhỏ có thể hoàn thành trong 30–60 phút. “Làm bài môn A” khá mơ hồ; “đọc chương 2 và ghi 5 ý chính” thì bắt đầu được ngay.</p><h3>Để lịch có khoảng trống</h3><p>Chỉ xếp khoảng 70% thời gian học dự kiến. Phần còn lại dành cho việc phát sinh, nghỉ ngơi và những ngày năng lượng thấp. Cuối tuần, xem lại việc gì đã xong và điều chỉnh tuần tới mà không tự trách mình.</p><p>Một kế hoạch hữu ích là kế hoạch giúp bạn quay lại sau khi lỡ nhịp, chứ không phải kế hoạch chưa từng bị phá vỡ.</p>"},
    {id:"memory",title:"Ôn bài để nhớ lâu: thử phương pháp nhớ chủ động",category:"Học tập",date:"2026-09-18",author:"Minh Lê",minutes:5,image:images.memory,excerpt:"Đọc lại thêm một lần thường tạo cảm giác quen thuộc. Tự nhớ lại mới giúp kiến thức ở lại lâu hơn.",content:"<p>Khi học, chúng ta dễ nhầm cảm giác quen mắt với việc thật sự nhớ. Thay vì đọc đi đọc lại một trang, hãy khép tài liệu và thử kể lại những gì vừa học bằng lời của mình.</p><h3>Ba bước ôn tập chủ động</h3><p>Sau mỗi phần nhỏ, đặt câu hỏi về ý chính. Viết hoặc nói câu trả lời mà không nhìn tài liệu. Cuối cùng mở lại để kiểm tra chỗ nào còn thiếu, rồi quay lại những câu đó sau một khoảng nghỉ.</p><p>Bạn có thể dùng thẻ ghi nhớ, tự làm đề ngắn hoặc giải thích bài cho một người bạn. Những lần nhớ lại cách nhau một ngày, ba ngày và một tuần thường hữu ích hơn một buổi học dồn thật dài.</p><h3>Biến nó thành thói quen nhỏ</h3><p>Thử dành năm phút cuối buổi học để tự kiểm tra. Không cần công cụ cầu kỳ: một trang giấy trắng cũng đủ để bắt đầu.</p>"},
    {id:"ai-study",title:"Dùng AI làm bạn học, đừng để AI học thay bạn",category:"Học tập",date:"2026-09-12",author:"Thảo Phạm",minutes:7,image:images.ai,excerpt:"AI có thể giải thích, đặt câu hỏi và gợi ý hướng tìm hiểu. Cách bạn kiểm tra câu trả lời vẫn rất quan trọng.",content:"<p>Hãy xem AI như một gia sư kiên nhẫn: bạn có thể yêu cầu giải thích khái niệm theo cách đơn giản, tạo câu hỏi luyện tập hoặc chỉ ra lỗ hổng trong lập luận của mình.</p><h3>Một vài câu lệnh có ích</h3><p>“Giải thích khái niệm này bằng ví dụ đời thường, sau đó hỏi mình ba câu để kiểm tra.” Hoặc: “Đây là phần mình tự giải. Đừng đưa đáp án ngay; hãy gợi ý bước tiếp theo.” Cách hỏi này giữ bạn ở vị trí chủ động.</p><h3>Luôn kiểm tra nguồn</h3><p>Mô hình có thể đưa thông tin nghe rất chắc chắn nhưng không đúng. Với dữ kiện quan trọng, hãy đối chiếu giáo trình, bài báo khoa học hoặc trang chính thức. Đừng đưa dữ liệu cá nhân hay tài liệu riêng tư vào công cụ bạn chưa hiểu rõ.</p><p>Hãy dùng AI để hỏi tốt hơn, rồi tự suy nghĩ, tự viết và ghi rõ sự hỗ trợ theo quy định của lớp học.</p>"},
    {id:"webdev",title:"Web Developer làm gì? Khám phá ba hướng đi phổ biến",category:"Hướng nghiệp",date:"2026-09-08",author:"Quân Trần",minutes:8,image:images.web,excerpt:"Từ giao diện người dùng đến máy chủ và dữ liệu — thế giới phát triển web có nhiều con đường.",content:"<p>Web Developer xây dựng và duy trì các ứng dụng chạy trên trình duyệt. Công việc thường kết hợp hiểu nhu cầu người dùng, giải quyết vấn đề kỹ thuật và phối hợp với thiết kế, sản phẩm.</p><h3>Frontend, backend và full-stack</h3><p>Frontend tập trung vào phần người dùng nhìn thấy và tương tác: HTML, CSS, JavaScript cùng một framework phổ biến. Backend xử lý dữ liệu, tài khoản, API và logic phía máy chủ. Full-stack làm việc ở cả hai phía, thường bắt đầu bằng một nền tảng vững rồi mở rộng dần.</p><h3>Nên học gì trước?</h3><p>Bắt đầu với HTML, CSS, JavaScript, Git và cách trình duyệt hoạt động. Sau đó làm một dự án nhỏ như trang giới thiệu câu lạc bộ hoặc ứng dụng ghi chú. Đưa dự án lên mạng, viết rõ bạn đã giải quyết vấn đề gì và điều gì sẽ cải thiện tiếp theo.</p><p>Không cần biết mình sẽ theo nhánh nào ngay từ đầu. Hãy thử làm sản phẩm nhỏ để tìm ra phần mình thích nhất.</p>"},
    {id:"teamwork",title:"Làm việc nhóm dễ thở hơn với một buổi khởi động tốt",category:"Kỹ năng",date:"2026-09-02",author:"An Nguyễn",minutes:5,image:images.group,excerpt:"Chốt mục tiêu, chia vai trò và cách liên lạc ngay từ đầu giúp cả nhóm bớt hiểu lầm.",content:"<p>Nhiều nhóm bắt đầu bằng câu “ai làm phần nào cũng được” rồi đến sát hạn mới phát hiện mỗi người hiểu đề một kiểu. Một buổi khởi động 20 phút có thể giúp tránh chuyện này.</p><h3>Thống nhất ba điều</h3><p>Đầu tiên là sản phẩm cuối cùng trông như thế nào và tiêu chí nào quan trọng. Tiếp theo là chia việc theo đầu ra cụ thể, có người phụ trách và hạn nội bộ sớm hơn hạn nộp. Cuối cùng, thống nhất nơi cập nhật tiến độ và cách báo khi có vướng mắc.</p><p>Chia nhỏ công việc giúp mỗi người biết mình cần bàn giao gì. Hẹn một lần kiểm tra giữa chặng để cả nhóm còn kịp điều chỉnh, thay vì chờ đến đêm cuối.</p>"},
    {id:"time",title:"Quản lý thời gian bằng cách chọn việc quan trọng trước",category:"Kỹ năng",date:"2026-08-27",author:"Minh Lê",minutes:6,image:images.time,excerpt:"Bận rộn cả ngày chưa chắc đã tiến gần điều mình muốn. Hãy bắt đầu bằng một ưu tiên rõ ràng.",content:"<p>Khi danh sách việc cần làm dài vô tận, mình hay chọn việc dễ nhất để gạch đi. Nhưng sau một ngày kín lịch, việc quan trọng nhất vẫn nằm nguyên đó.</p><h3>Thử chọn ba việc mỗi ngày</h3><p>Viết ra mọi thứ đang ở trong đầu, sau đó đánh dấu một việc quan trọng, hai việc cần thiết và những việc có thể chờ. Bắt đầu với việc quan trọng trong một khoảng tập trung ngắn trước khi mở mạng xã hội hay email.</p><p>Chia thời gian thành khối 25–50 phút và nghỉ ngắn giữa các khối. Nếu lịch bị lệch, chọn lại ưu tiên kế tiếp thay vì cố nhồi toàn bộ phần còn lại vào buổi tối.</p>"},
    {id:"ai-career",title:"AI Engineer là gì và cần chuẩn bị những gì?",category:"Hướng nghiệp",date:"2026-08-20",author:"Thảo Phạm",minutes:8,image:images.aiCareer,excerpt:"Tìm hiểu công việc phía sau những hệ thống thông minh và lộ trình nền tảng để bắt đầu.",content:"<p>AI Engineer xây dựng, tích hợp và vận hành các hệ thống sử dụng học máy hoặc mô hình AI. Tùy công ty, công việc có thể nghiêng về dữ liệu, nghiên cứu ứng dụng hoặc đưa mô hình vào sản phẩm thật.</p><h3>Nền tảng nên xây dựng</h3><p>Python, cấu trúc dữ liệu, đại số tuyến tính, xác suất và thống kê là những điểm khởi đầu có ích. Sau đó học cách xử lý dữ liệu, đánh giá mô hình và triển khai dịch vụ. Một dự án nhỏ với dữ liệu công khai giúp bạn thực hành cả quy trình.</p><p>Không cần chạy theo mọi mô hình mới. Hiểu dữ liệu, biết đo kết quả và trình bày giới hạn của giải pháp là những kỹ năng bền vững.</p>"},
    {id:"cv",title:"CV đầu tiên: kể câu chuyện của bạn bằng một trang giấy",category:"Hướng nghiệp",date:"2026-08-14",author:"Quân Trần",minutes:5,image:images.cv,excerpt:"Chưa có nhiều kinh nghiệm vẫn có thể làm nổi bật dự án, hoạt động và điều bạn đã học được.",content:"<p>CV đầu tiên không cần chứng minh bạn đã biết tất cả. Nó cần giúp người đọc thấy bạn có nền tảng gì, đã chủ động làm điều gì và có thể đóng góp ra sao.</p><h3>Đưa bằng chứng cụ thể</h3><p>Thay “có kỹ năng làm việc nhóm”, hãy mô tả dự án bạn phối hợp, vai trò của bạn và kết quả đạt được. Đồ án môn học, hoạt động câu lạc bộ, tình nguyện hay dự án cá nhân đều có thể cho thấy cách bạn làm việc.</p><p>Giữ bố cục gọn, kiểm tra lỗi chính tả và điều chỉnh nội dung theo vị trí đang ứng tuyển. Khi phỏng vấn, chuẩn bị kể ngắn gọn một thử thách bạn gặp và cách bạn xử lý.</p>"}
  ];
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
  let posts=read(KEY,initial),activeId=null;const grid=document.getElementById("articleGrid"),search=document.getElementById("search"),category=document.getElementById("category");
  const formatDate=value=>new Intl.DateTimeFormat("vi-VN",{day:"numeric",month:"long",year:"numeric"}).format(new Date(value+"T00:00:00"));
  function renderCards(){const q=search.value.trim().toLocaleLowerCase("vi"),cat=category.value;const found=posts.filter(p=>(cat==="all"||p.category===cat)&&(p.title+" "+p.excerpt+" "+p.author+" "+p.category).toLocaleLowerCase("vi").includes(q));grid.innerHTML=found.map(p=>{const liked=read("cham-like-"+p.id,false);return '<article class="article-card" data-open="'+esc(p.id)+'"><div class="article-image" style="background-image:url(&quot;'+esc(p.image)+'&quot;)"><span class="tag">'+esc(p.category.toUpperCase())+'</span></div><div class="article-body"><div class="article-meta">'+formatDate(p.date)+' · '+p.minutes+' PHÚT ĐỌC</div><h3>'+esc(p.title)+'</h3><p>'+esc(p.excerpt)+'</p><div class="article-foot"><span class="author">Bởi '+esc(p.author)+'</span><span class="read-link">Đọc bài →</span><button class="like-btn '+(liked?"liked":"")+'" data-like="'+esc(p.id)+'" aria-label="Yêu thích bài viết">'+(liked?"♥":"♡")+'</button></div></div></article>'}).join("");document.getElementById("emptyState").hidden=found.length>0}
  function openArticle(id){const p=posts.find(x=>x.id===id);if(!p)return;activeId=id;document.getElementById("articleDetail").innerHTML='<div class="detail-image" style="background-image:url(&quot;'+esc(p.image)+'&quot;)"></div><div class="detail-meta">'+esc(p.category)+' · '+formatDate(p.date)+' · '+p.minutes+' phút đọc · Bởi '+esc(p.author)+'</div><h1 class="detail-title">'+esc(p.title)+'</h1><div class="detail-content">'+p.content+'</div>';renderComments();document.getElementById("articleDialog").showModal()}
  function renderComments(){const list=read("cham-comments-"+activeId,[]);document.getElementById("commentList").innerHTML=list.length?list.map(c=>'<div class="comment"><strong>'+esc(c.name)+'</strong><time>'+esc(c.date)+'</time><p>'+esc(c.text)+'</p></div>').join(""):'<p class="article-meta">Chưa có bình luận. Bạn sẽ là người đầu tiên!</p>'}
  grid.addEventListener("click",e=>{const like=e.target.closest("[data-like]");if(like){const key="cham-like-"+like.dataset.like;localStorage.setItem(key,JSON.stringify(!read(key,false)));renderCards();return}const card=e.target.closest("[data-open]");if(card)openArticle(card.dataset.open)});
  search.addEventListener("input",renderCards);category.addEventListener("change",renderCards);
  document.querySelectorAll(".topic-card").forEach(b=>b.addEventListener("click",()=>{category.value=b.dataset.filter;renderCards();document.getElementById("articles").scrollIntoView({behavior:"smooth"})}));
  document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));
  document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));
  document.getElementById("commentForm").addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),key="cham-comments-"+activeId,list=read(key,[]);list.push({name:d.get("name").trim(),text:d.get("text").trim(),date:new Intl.DateTimeFormat("vi-VN",{dateStyle:"medium"}).format(new Date())});localStorage.setItem(key,JSON.stringify(list));f.reset();renderComments()});
  document.getElementById("newsletterForm").addEventListener("submit",e=>{e.preventDefault();const email=document.getElementById("email").value.trim(),list=read("cham-newsletter-v1",[]);if(!list.includes(email))list.push(email);localStorage.setItem("cham-newsletter-v1",JSON.stringify(list));document.getElementById("newsletterMessage").textContent="Bạn đã đăng ký rồi! Hẹn gặp bạn trong thư tiếp theo ✳";e.currentTarget.reset()});
  const menu=document.querySelector(".menu-toggle"),nav=document.querySelector(".nav");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open));menu.setAttribute("aria-label",open?"Đóng menu":"Mở menu")});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}));
  const adminDialog=document.getElementById("adminDialog"),adminContent=document.getElementById("adminContent");document.getElementById("adminOpen").addEventListener("click",()=>{renderAdmin();adminDialog.showModal()});
  function renderAdmin(){if(!sessionStorage.getItem(ADMIN_KEY)){adminContent.innerHTML='<h2>Khu vực quản trị</h2><p class="article-meta">Đăng nhập bản demo để thêm, sửa hoặc xóa bài viết.</p><form id="adminLogin" class="admin-login"><label>Tên đăng nhập<input name="user" autocomplete="username" required></label><label>Mật khẩu<input name="password" type="password" autocomplete="current-password" required></label><button class="button">Đăng nhập ↗</button><small>Tài khoản demo: admin / cham2026</small></form>';document.getElementById("adminLogin").addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(d.get("user")==="admin"&&d.get("password")==="cham2026"){sessionStorage.setItem(ADMIN_KEY,"1");renderAdmin()}else toast("Thông tin đăng nhập chưa đúng.")});return}
    adminContent.innerHTML='<h2>Quản lý bài viết</h2><p class="article-meta">Dữ liệu được lưu trên trình duyệt này. Tài khoản quản trị demo.</p><form class="admin-form" id="postForm"><input type="hidden" name="id"><label>Tiêu đề<input name="title" maxlength="120" required></label><label>Chuyên mục<select name="category"><option>Học tập</option><option>Hướng nghiệp</option><option>Kỹ năng</option></select></label><label>Tác giả<input name="author" maxlength="50" required></label><label>Ảnh (URL)<input name="image" type="url" required></label><label class="wide">Mô tả ngắn<textarea name="excerpt" maxlength="220" required></textarea></label><label class="wide">Nội dung HTML<textarea name="content" required></textarea></label><button class="button">Lưu bài viết ↗</button><button type="button" class="button button-lime" id="adminLogout">Đăng xuất</button></form><div class="admin-list">'+posts.map(p=>'<div class="admin-row"><span>'+esc(p.title)+' <small>· '+esc(p.category)+'</small></span><span><button data-edit="'+esc(p.id)+'">Sửa</button> <button data-delete="'+esc(p.id)+'">Xóa</button></span></div>').join("")+'</div>';
    const form=document.getElementById("postForm");form.addEventListener("submit",e=>{e.preventDefault();const d=new FormData(form),id=d.get("id")||"post-"+Date.now(),old=posts.find(p=>p.id===id),content=d.get("content"),post={id,title:d.get("title").trim(),category:d.get("category"),author:d.get("author").trim(),image:d.get("image").trim(),excerpt:d.get("excerpt").trim(),content,date:old?.date||new Date().toISOString().slice(0,10),minutes:Math.max(1,Math.ceil(content.replace(/<[^>]*>/g," ").split(/\s+/).length/180))};posts=old?posts.map(p=>p.id===id?post:p):[post,...posts];localStorage.setItem(KEY,JSON.stringify(posts));renderCards();renderAdmin();toast("Đã lưu bài viết.")});
    adminContent.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>{const p=posts.find(x=>x.id===b.dataset.edit);Object.entries(p).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});form.scrollIntoView({behavior:"smooth"})}));
    adminContent.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>{posts=posts.filter(p=>p.id!==b.dataset.delete);localStorage.setItem(KEY,JSON.stringify(posts));renderCards();renderAdmin();toast("Đã xóa bài viết.")}));document.getElementById("adminLogout").addEventListener("click",()=>{sessionStorage.removeItem(ADMIN_KEY);renderAdmin()})}
  function toast(message){const el=document.createElement("div");el.className="toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2400)}
  document.getElementById("year").textContent=new Date().getFullYear();renderCards();
})(); 
